### PR TITLE
Create merged analysis report for Sequel analysis jobs

### PR DESCRIPTION
**Pull request by ces**
Create merged json file from up to ~100 report files produced by SMRT Link ccs/deplex analysis jobs. Archive to iRODS.

### CODE REVIEW

**Review by kjsanger — COMMENTED** [review]
This looks good to me - clear, documented and tested. One question/comment - is there a compelling reason to pull in the MooseX::Storage framework as a dependency? It looks like the JSON (de)serialization could be done with the basic JSON module.

**Comment by kjsanger** [comment]
Would you mind squashing to a single commit? Looks like the first commit message is the best.

**Comment by ces** [comment]
> This looks good to me - clear, documented and tested. One question/comment - is there a compelling reason to pull in the MooseX::Storage framework as a new dependency? It looks like the JSON (de)serialization could be done with the basic JSON module.

I had trouble with correct deserialization with the basic module due to the slightly more complex structure.

**Comment by ces** [comment]
> Would you mind squashing to a single commit? Looks like the first commit message is the best.

I was hoping Merge 'Squash and merge' would be okay ?

**Pull request merged**
