### PR TITLE
Added a TreePublisher to support Illumina and 10X run publishing.

### PR DESCRIPTION
**Pull request by kjsanger**
Refactored the tree-publish code originally internal to the Illumina
RunPublisher into a new class to be used more widely. The Illumina
RunPublisher now uses the TreePublisher and its associated error
counter to record publishing errors more accurately than the version
it replaces.

### CODE REVIEW

**Comment by mgcam** [comment]
Comment re https://github.com/wtsi-npg/npg_irods/blob/fcb0ebbd6467cd460d780acd33f834608c9335a1/lib/WTSI/NPG/HTS/Illumina/RunPublisher.pm#L198

Early return of three values while at the end there is no explicit return. No colling code captures return of this  anonimous function. It wiuld be better to have simply `return;` both at the end and when returning early.

**Comment by kjsanger** [comment]
No, there is an explicit return from the method here: https://github.com/wtsi-npg/npg_irods/blob/fcb0ebbd6467cd460d780acd33f834608c9335a1/lib/WTSI/NPG/HTS/Illumina/RunPublisher.pm#L246

Aha, thanks - I'm missing a closing brace on the anonymous function.

Calling code is intended to capture the return value of the anonymous function here https://github.com/wtsi-npg/npg_irods/blob/fcb0ebbd6467cd460d780acd33f834608c9335a1/lib/WTSI/NPG/HTS/Illumina/RunPublisher.pm#L202 and add the values to the running total here https://github.com/wtsi-npg/npg_irods/blob/fcb0ebbd6467cd460d780acd33f834608c9335a1/lib/WTSI/NPG/HTS/Illumina/RunPublisher.pm#L214-L216

**Comment by mgcam** [comment]
> Agreed ... ignore my earlier reply! Now I've had coffee I see what you mean.
Many brackets, difficult to see. There might be a way to slightly simplify this, but I do not feel it belongs to this pr. It seems that we inherited some features from the old publisher which we can do without. Probably we need to look into this in future.

**Comment by kjsanger** [comment]
Upfated MANIFEST file.

**Pull request merged**
