### PR TITLE
Corrected is_paired_read behaviour and added missing test.

### PR DESCRIPTION
**Pull request by kjsanger**

### CODE REVIEW

**Comment by mgcam** [comment]
The loop for reading the SAM reads https://github.com/wtsi-npg/npg_irods/blob/41f2e7d0ca619896a786db6494120398340040fc/lib/WTSI/NPG/HTS/Illumina/AlnDataObject.pm#L323 should have an early exit if the the number of reads is smaller that requested.

something like while((my $line = <$fh>) && ($count < $num_requested) {} might work

**Comment by mgcam** [comment]
There is no way to determine the paired flag from sequencing data in case of no reads, which is not infrequent for phix split out data. Could we have a situation where within the same run some data are flagged as paired and some as unpaired? We have a similar problem in qc checks, which we resolved by passing the flag from the pipeline. It might be that passing a flag to the publisher is a good solution, then falling back to this code if the flag if not explicitly set.

**Comment by kjsanger** [comment]
In that case I'd argue that the publisher should not be checking at all and the flag should always be passed in to it.

**Comment by srl147** [comment]
this would explain why when I found a single-ended cram file with is_paired set to 1 the corresponding phix cram file almost always had is_paired set to 0

**Comment by mgcam** [comment]
> In that case I'd argue that the publisher should not be checking at all and the flag should always be passed in to it.

Looks like it

**Pull request merged**
